setup-environment: fix setting custom OSTree commit message
This fixes the following build error when OSTree commit
message is set:

INFO: Starting rpi3 OSTree repo build...
DEBUG: OSTree commit message: "Added custom compose apps"
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.
Usage:  docker buildx build [OPTIONS] PATH | URL | -
Start a build
Error: Process completed with exit code 1.

Signed-off-by: Matija Tudan <matija.tudan@nulix.hr>